In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_with = pd.read_excel('/home/peng/PycharmProjects/featurematch/model/withoutgene_omim_with_patients/evaluation.xlsx')
df_without = pd.read_excel('/home/peng/PycharmProjects/featurematch/model/withoutgene_omim_without_patients/evaluation.xlsx')[['rank_hpo']]

df = pd.concat([df_with, df_without], axis=1)
df['c']= np.negative(np.log(df.rank_withp/df.rank_hpo))

df.to_excel('c.xlsx', index=None)

In [9]:
df

,patient_id,omim_id,No.patients,features,No.features,results_withp,rank_withp,rank_hpo,c
0,Patient:208664,Larsen Syndrome; LRS,6,"Short stature,Elbow dislocation,Congenital kne...",13,"['Larsen Syndrome; LRS', '#108721 ATELOSTEOGEN...",1,1,-0.000000
1,Patient:208659,Larsen Syndrome; LRS,6,"Short stature,Knee dislocation,Congenital hip ...",16,"['Larsen Syndrome; LRS', 'SPONDYLOEPIMETAPHYSE...",1,1,-0.000000
2,Patient:222155,"Microcephaly, Primary Autosomal Recessive",1,"Absent speech,Intellectual disability, severe,...",3,['Hyperphosphatasia with Mental Retardation Sy...,306,369,0.187212
3,Patient:222306,Marshall Syndrome; MRSHS,6,"Depressed nasal bridge,Cleft palate,Micrognath...",9,"['Marshall Syndrome; MRSHS', '275595 TRIGONOBR...",1,2,0.693147
4,Patient:222308,Marshall Syndrome; MRSHS,6,"Depressed nasal bridge,Cleft palate,Arthralgia...",14,"['Marshall Syndrome; MRSHS', '#215150 OTOSPOND...",1,1,-0.000000
...,...,...,...,...,...,...,...,...,...
239,Patient:51561,Rubinstein-Taybi Syndrome,13,"Inappropriate laughter,Hypokinesia,Hypersomnia...",40,"['227210 EYEBROWS, DUPLICATION OF, WITH STRETC...",420,218,-0.655760
240,Patient:40643,Smith-Lemli-Opitz Syndrome; SLOS,9,"Delayed speech and language development,Short ...",16,"['SYNPOLYDACTYLY 1', 'CLEFT PALATE, DEAFNESS, ...",211,386,0.603979
241,Patient:47450,Sotos Syndrome,24,"Hypoplasia of the corpus callosum,Hydrocele te...",18,"['Sotos Syndrome', 'Phelan-Mcdermid Syndrome; ...",1,6,1.791759
242,Patient:130011,"Trichorhinophalangeal Syndrome , Type I; TRPS1",8,"Short 3rd finger,Underdeveloped nasal alae,Abs...",14,"['Trichorhinophalangeal Syndrome , Type I; TRP...",1,3,1.098612
243,Patient:52586,"Trichorhinophalangeal Syndrome , Type I; TRPS1",8,"Short hallux,Short finger,Flat nasal alae,Fine...",20,"['SYNDACTYLY, TYPE III', 'ODONTOMICRONYCHIAL D...",3,23,2.036882

In [2]:
import os
from CADA.paths import DATA_DIRECTORY
import pandas as pd


hpoteam=True
predicate = 'is_feature_of_disease'
triples = []
if hpoteam:
    input_file = os.path.join(DATA_DIRECTORY, 'raw', 'hpo', 'disease-hpo', 'phenotype_annotation_hpoteam.tab')
else:
    input_file = os.path.join(DATA_DIRECTORY, 'raw', 'hpo', 'disease-hpo', 'phenotype_annotation.tab')

print(input_file)

/home/peng/PycharmProjects/featurematch/data/raw/hpo/disease-hpo/phenotype_annotation_hpoteam.tab

In [11]:
df = pd.read_csv(input_file, sep ='\t', header=None).applymap(str)
df = df.loc[df.iloc[:,0] == 'OMIM']

In [12]:
df.iloc[:,1] = 'OMIM:' + df.iloc[:,1]

In [13]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
285,OMIM,OMIM:100050,"100050 AARSKOG SYNDROME, AUTOSOMAL DOMINANT",nan,HP:0000028,OMIM:100050,IEA,nan,nan,nan,P,nan,HPO:skoehler,nan
286,OMIM,OMIM:100050,"100050 AARSKOG SYNDROME, AUTOSOMAL DOMINANT",nan,HP:0000049,OMIM:100050,IEA,nan,nan,nan,P,nan,HPO:iea,nan
287,OMIM,OMIM:100050,"100050 AARSKOG SYNDROME, AUTOSOMAL DOMINANT",nan,HP:0000175,OMIM:100050,TAS,nan,nan,nan,P,nan,HPO:probinson,nan
288,OMIM,OMIM:100050,"100050 AARSKOG SYNDROME, AUTOSOMAL DOMINANT",nan,HP:0000202,OMIM:100050,IEA,nan,nan,nan,P,nan,HPO:skoehler,nan
289,OMIM,OMIM:100050,"100050 AARSKOG SYNDROME, AUTOSOMAL DOMINANT",nan,HP:0000204,OMIM:100050,TAS,nan,nan,nan,P,nan,HPO:probinson,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100401,OMIM,OMIM:618492,neurodevelopmental disorder with microcephaly ...,nan,HP:0001331,PMID:31079899,PCS,nan,HP:0040284,nan,P,NEURODEVELOPMENTAL DISORDER WITH MICROCEPHALY ...,HPO:probinson,1/3
100402,OMIM,OMIM:618492,neurodevelopmental disorder with microcephaly ...,nan,HP:0002079,PMID:31079899,PCS,nan,HP:0040284,nan,P,NEURODEVELOPMENTAL DISORDER WITH MICROCEPHALY ...,HPO:probinson,1/3
100403,OMIM,OMIM:618492,neurodevelopmental disorder with microcephaly ...,nan,HP:0007018,PMID:31079899,PCS,nan,HP:0040284,nan,P,NEURODEVELOPMENTAL DISORDER WITH MICROCEPHALY ...,HPO:probinson,3/3
100404,OMIM,OMIM:618492,neurodevelopmental disorder with microcephaly ...,nan,HP:0009879,PMID:31079899,PCS,nan,HP:0040284,nan,P,NEURODEVELOPMENTAL DISORDER WITH MICROCEPHALY ...,HPO:probinson,3/3
100405,OMIM,OMIM:618492,neurodevelopmental disorder with microcephaly ...,nan,HP:0010864,PMID:31079899,PCS,nan,HP:0040284,nan,P,NEURODEVELOPMENTAL DISORDER WITH MICROCEPHALY ...,HPO:probinson,5/5